src/generateTypes.ts, src/lib/addInterfacePropertiesForFields.ts, src/lib/addTypeAliasForCustomType.ts, src/lib/addTypeAliasForSharedSlice.ts, src/types.ts, test/generateTypes-embed.test.ts
This PR adds the ability to type Embed fields with custom provider-specific types.
For example, if you expect YouTube links to be provided via an Embed field, and you know the oEmbed data that will be provided, you can configure the output to include your custom type.
Custom types can be provided to `generateTypes()`'s `fieldConfigs.embed.providerTypes` option:
```typescript
const model = prismicM.model.customType({
seed: t.title,
id: "foo",
fields: {
bar: prismicM.model.embed({ seed: t.title }),
},
});
const types = generateTypes({
customTypeModels: [model],
fieldConfigs: {
embed: {
providerTypes: {
YouTube: "YouTubeType",
Vimeo: "VimeoType",
},
},
},
});
```
This will provide the following output (this is not the full output, only the relevant part):
```typescript
interface …
```
=> feat: support custom Embed data with provider-specific types

package-lock.json, package.json, src/lib/addInterfacePropertiesForFields.ts, src/types.ts, test/generateTypes-integrationFields.test.ts
This PR adds the ability to type Integration Fields fields with custom catalog-specific types.
For example, if you know the object type returned by a Shopify catalog, you can configure the output to include your custom type.
Custom types can be provided to `generateTypes()`'s `fieldConfigs.integrationFields.catalogTypes` option:
```typescript
const model = prismicM.model.customType({
seed: t.title,
id: "foo",
fields: {
bar: prismicM.model.integrationFields({
seed: t.title,
catalog: "baz"
}),
},
});
const types = generateTypes({
customTypeModels: [model],
fieldConfigs: {
integrationFields: {
catalogTypes: {
baz: "BazType",
},
},
},
});
```
This will provide the following output (this is not the full output, only the relevant part):
```typescript
interface FooDocumentData {
bar: …
```
=> feat: support custom Integration Fields data with catalog-specific types

src/lib/addInterfacePropertiesForFields.ts, test/generateTypes-customType.test.ts, test/generateTypes-group.test.ts, test/generateTypes-sharedSlice.test.ts, test/generateTypes-sliceZone.test.ts
Closes https://github.com/prismicio/prismic-ts-codegen/issues/6
Codegen was failing if a field name included hyphens.
This PR sets the value correctly using a template literal and wrapping in quotes.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
```typescript
interface Example {
my-field: string;
}
```
</td>
<td>
```typescript
interface Example {
"my-field": string;
}
```
</td>
</tr>
</table>
=> fix: support fields with hyphenated API IDs

src/lib/addInterfacePropertiesForFields.ts, src/lib/addTypeAliasForCustomType.ts, src/lib/buildFieldDocs.ts, src/lib/writeFieldDocsDescription.ts
This PR adds a Custom Type field's tab name to its description. Since Shared Slices are generated as a shared type potentially used by multiple Custom Types, Shared Slice fields do not list their tab names.
A field's description looks like this:
```
/**
* main_title field in *Tabbed Page*
*
* - **Field Type**: Title
* - **Placeholder**: *None*
* - **API ID Path**: tabbed_page.main_title
* - **Tab**: Main
* - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
*/
```
Note the "Tab" bullet point.
=> feat: add a Custom Type field's tab name to its description

src/lib/addInterfacePropertiesForFields.ts, test/generateTypes-customType.test.ts
This PR fixes a bug where `prismic-ts-codegen` would crash if it came across a field API ID starting with a number.
For example, a field with the API ID of `3d-noodle` would cause the following error:
```
ManipulationError: Manipulation error: A syntax error was inserted.
types.d.ts:2910:6 - error TS1351: An identifier or keyword cannot immediately follow a numeric literal.
```
This PR fixes this issue by wrapping those field name properties with quotation parts (e.g. `"3d-noodle"`).
For more details, see #24. Thanks to @AugusDogus for reporting the issue!
🍝
=> fix: support fields with a name starting with a number

src/lib/addInterfacePropertiesForFields.ts, test/generateTypes-image.test.ts
This PR changes the generated type for Image fields without thumbnails to use the latest `@prismicio/types` recommendation.
- OLD: `ImageField<null>`
- NEW: `ImageField<never>`
`null` will continue to work, but it is deprecated in `@prismicio/types`. Similarly, `never` was supported in previous versions of `@prismicio/types`, but it was not the recommended API. That recommendation has changed.
See https://github.com/prismicio/prismic-types/pull/46 for more details.
=> fix: use `ImageField<never>` rather than `ImageField<null>`

src/cli/loadConfig.ts
This PR fixes a bug in the `prismic-ts-codegen` CLI where custom configuration files specified with the `--config/-c` option were loaded incorrectly.
As of this PR, custom configuration files are loaded using the same logic as the default configuration file.
```typescript
// custom-config.ts
import type { Config } from "prismic-ts-codegen";
const config: Config = {
repositoryName: "qwerty",
// ...etc.
};
// `export default` is now supported (recommended)
export default config;
// `module.exports` is also supported (not recommended)
module.exports = config;
```
Fixes #31
🐤
=> fix(cli): support custom configs via `--config/-c` with a default export

src/generateTypes.ts, test/generateTypes.test.ts
This PR fixes a bug where the `@prismicio/client` integration would return `any` for all client query methods.
This only occurs when `@prismicio/types` is used as the types provider (the default). Both `@prismicio/types` and `@prismicio/client` were imported as `prismic`, causing a type error. Without a resolvable type, TypeScript returns `any`.
```typescript
// Output before
import type * as prismic from "@prismicio/types";
import type * as prismic from "@prismicio/client"; // Conflict!
// Output after
import type * as prismic from "@prismicio/types";
import type * as prismicClient from "@prismicio/client";
```
Note that when `@prismicio/client` is the types provider, only a single import is generated, resulting in no error.
```typescript
import type * as prismic from …
```
=> fix: restore `@prismicio/client` integration

src/lib/addInterfacePropertiesForFields.ts, test/generateTypes-contentRelationship.test.ts
This PR updates content relationship field's type from the depreacted `RelationField` to `ContentRelationshipField`.
`RelationField` was deprecated and replaced by `ContentRelationshipField` in `@prismicio/types` v0.2.3.
`RelationField` was removed in `@prismicio/client` v7.0.0 as part of the `@prismicio/types` -> `@prismicio/client` merge.
🐏
=> fix: update content relationship field type from the deprecated `RelationField` to `ContentRelationshipField`

package-lock.json, package.json, src/lib/addInterfacePropertiesForFields.ts, test/generateTypes-integration.test.ts
This PR fixes `prismic-ts-codegen` by using the correct non-deprecated `IntegrationField` type.
`IntegrationFields` (with an "s") was deprecated in `@prismicio/client` v7. Although `IntegrationFields` is still a valid API, TypeScript will warn about its deprecation status, and the type will eventually be removed from `@prismicio/cilent`.
🐰
=> fix: replace deprecated `IntegrationFields` type with `IntegrationField` type

src/lib/buildCustomTypeDataType.ts, src/lib/buildCustomTypeType.ts, src/lib/buildFieldDocs.ts, src/lib/buildFieldProperties.ts, src/lib/buildSharedSliceType.ts, src/lib/checkHasUIDFIeld.ts, vite.config.ts
This PR restores compatibility with `@prismicio/client` v6 as a peer dependency.
`prismic-ts-codegen` v0.1.12 makes use of `@prismicio/client` v7's enums and types.
This PR replaces enum usage with strings (which remains type-checked). It also inlines `@prismicio/client` v7 as a dependency which should only be used at build time for types.
=> fix: compatibility with `@prismicio/client` v6

src/lib/buildUnion.ts, test/generateTypes-sliceZone.test.ts
This PR fixes a bug where Slice Zones with no choices resulted in invalid syntax.
=> fix: restore support for Slice Zones without choices

bin/prismic-ts-codegen.js, bin/prismic-ts-codegen.mjs, package.json, vite.config.ts
CLI is broken due to the way `@prismicio/client` is treated since `0.1.12`. This can be reproduced anywhere by simply running: `npx prismic-ts-codegen@0.1.16`.
This PR solves it by using the CJS export of the CLI which has proved more stable in the case of Slice Machine ([init](https://github.com/prismicio/slice-machine/blob/c3a5117c0d35e86020df6b5d16dd600e4231fda3/packages/init/bin/slicemachine-init.js), [start](https://github.com/prismicio/slice-machine/blob/c3a5117c0d35e86020df6b5d16dd600e4231fda3/packages/start-slicemachine/bin/start-slicemachine.js)). This forces us however to inline ESM-only dependencies (see Vite config)
Resolves: #56
=> fix(cli): prevent `"Named export 'createClient' not found"` error

src/cli/index.ts
Allow other tools calling prismic-ts-codegen to detect errors by returning non-zero exit code from the process when errors occur.
The change signals a non-zero exit code (1) when prismic-ts-codegen execution end with an error. 
Currently if the tool is used in an automated build process, there is no way to interrupt the build other than scanning stdout for errors.
Using a non-zero code is a [standard practice](https://en.wikipedia.org/wiki/Exit_status) allowing other tools to detect failure scenarios.
=> fix(cli): exit with non-zero error code when CLI has errors

.github/workflows/ci.yml, package-lock.json, package.json, src/generateTypes.ts, src/lib/buildFieldProperties.ts, src/lib/buildSharedSliceType.ts, test/__snapshots__/generateTypes.test.ts.snap, test/generateTypes-sharedSlice.test.ts
> [!IMPORTANT]
> **Required before merging this PR:**
> - [ ] Update `@prismicio/types-internal` once https://github.com/prismicio/prismic-types-internal/pull/70 is merged.
> - [ ] Remove `--legacy-peer-deps` from the CI workflow.
This PR adds support for group fields in slices. This is an upcoming Prismic feature.
**Context**: [DT-2096](https://linear.app/prismic/issue/DT-2096/aadevuser-i-can-see-generated-typescript-types-for-group-field-content)
=> feat: support group fields in slices

CHANGELOG.md, package-lock.json, package.json, src/lib/buildFieldProperties.ts, test/generateTypes-group.test.ts, test/generateTypes-sharedSlice.test.ts
> [!CAUTION]
> Complete before merging:
> - [ ] Merge and publish https://github.com/prismicio/prismic-client/pull/341.
> - [ ] Update `@prismicio/client` in this PR to the non-alpha version.
> - [ ] Update `@prismicio/mock` in this PR to the non-alpha version.
> - [ ] Remove `overrides` property in `package.json`.
**Resolves**: [DT-2137](https://linear.app/prismic/issue/DT-2137/aaprismicdev-prismic-ts-codegen-support-advanced-groups)
This PR adds support for group fields nested within group fields. This is an upcoming Prismic feature.
TODO
TODO
[^1]: Please use these labels when submitting a review:
:bulb: #idea:&ensp;Suggest an idea.
:warning: #issue:&ensp;Strongly suggest a change.
:tada: #nice:&ensp;Share a complement.
=> feat: support groups in groups

package-lock.json, package.json, src/generateTypes.ts, test/__snapshots__/generateTypes.test.ts.snap, test/generateTypes.test.ts
> [!IMPORTANT]
> This PR is only to be reviewed once we're aligned on the [upstream client PR](https://github.com/prismicio/prismic-client/pull/350).
**Resolves**: required after https://github.com/prismicio/prismic-client/pull/350
This is a downstream PR related to this bigger `@prismicio/client` PR: https://github.com/prismicio/prismic-client/pull/350
It adds additional module augments for the new `WriteClient` and `Migration` classes introduced in `@prismicio/client`
See snapshot: https://github.com/prismicio/prismic-ts-codegen/pull/65/files#diff-da5cd8935e1941a082f260623158b3a2a0a41fd54bf297b36c15f00ad4afe165
[^1]:
Please use these labels when submitting a review:
:bulb: #idea:&ensp;Suggest an idea.
:warning: #issue:&ensp;Strongly suggest a …
=> feat: support new `@prismicio/client`'s `WriteClient`

CHANGELOG.md, package-lock.json, package.json, src/lib/buildFieldProperties.ts, test/__snapshots__/generateTypes.test.ts.snap, test/generateTypes-link.test.ts, test/generateTypes-linkToMedia.test.ts
**Resolves**: 
https://linear.app/prismic/issue/DT-2426/aauser-in-slice-machine-when-i-create-a-new-link-with-repeat-property
[^1]:
Please use these labels when submitting a review:
:bulb: #idea:&ensp;Suggest an idea.
:warning: #issue:&ensp;Strongly suggest a change.
:tada: #nice:&ensp;Share a compliment.
=> feat: support repeatable links

src/lib/buildFieldDocs.ts, src/lib/buildFieldProperties.ts, test/__snapshots__/generateTypes.test.ts.snap, test/generateTypes-title.test.ts
Resolves: N/A
This PR replaces uses of `TitleField` with `RichTextField`. The title field does not exist in Slice Machine and is not something we support in new projects.
`@prismicio/client` will continue to have `TitleField` to support legacy projects. However, generated types will revert to `RichTextField`.
In practice, this change only affects the TSDocs a developer will see in their editor.
[^1]:
Please use these labels when submitting a review:
:bulb: #idea:&ensp;Suggest an idea.
:warning: #issue:&ensp;Strongly suggest a change.
:tada: #nice:&ensp;Share a compliment.
=> fix: replace `TitleField` with `RichTextField`

.github/workflows/ci.yml, src/constants.ts, src/lib/buildFieldDocs.ts, test/__snapshots__/generateTypes.test.ts.snap
Resolves: N/A
This PR updates the documentation URLs used in the generated TSDocs. The documentation URLs changed within the past few months as part of a documentation refresh effort.
The old URLs have redirects to reasonably close pages, so users who don't update to the latest version will not encounter 404 pages.
> [!NOTE]
> The CI's Node.js and TypeScript versions were updated as part of this PR. I changed the code to use `satisfies`, which wasn't introduced until TypeScript 4.9.
>
> I added the most popular TypeScript versions according to https://majors.nullvoxpopuli.com/q?minors=true&old=false&packages=typescript.
>
> The Node.js versions match current LTS versions.
[^1]:
Please use these labels when submitting a review:
:bulb: …
=> fix: update documentation URLs to the latest version
